---
strictness: veryhigh
max-line-length: 110
doc-warnings: true

ignore-paths:
  - tilecloud_chain/configuration.py

pylint:
  disable:
    - too-many-statements
    - too-many-branches
    - too-many-instance-attributes
    - too-many-locals
    - too-many-return-statements
    - too-many-boolean-expressions
    - too-many-arguments
    - too-many-nested-blocks
    - too-many-lines
    - too-many-public-methods
    - too-few-public-methods
    - wrong-import-order # done by isore
    - line-too-long # done by black
    - no-else-return
    - no-else-break
    - invalid-name
    - broad-except
    - abstract-method
    - duplicate-string-formatting-argument
    - cyclic-import
    - missing-module-docstring
    - missing-function-docstring

pep8:
  disable:
    - E203 # Whitespace before ':'
    - E722 # Do not use bare 'except'
    - E501 # Line too long

pep257:
  disable:
    - D100 # Missing docstring in public module
    - D102 # Missing docstring in public method
    - D104 # Missing docstring in public package
    - D107 # Missing docstring in __init__
    - D203 # 1 blank line required before class docstring (found 0)
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section ('Arguments')
    - D412 # No blank lines allowed between a section header and its content ('Arguments')
    - D413 # Missing blank line after last section ('Arguments')

mypy:
  run: true

mccabe:
  run: false

bandit:
  run: true
  options:
    config: .bandit.yaml
