inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

doc-warnings: true

ignore-paths:
  - tilecloud_chain/configuration.py

pylint:
  disable:
    - missing-timeout # done globally by c2cwsgiutils

pydocstyle:
  disable:
    - D202 # No blank lines allowed after function docstring
    - D104 # Missing docstring in public package
    - D107 # Missing docstring in __init__

bandit:
  options:
    config: .bandit.yaml
