inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:c2cwsgiutils
  - duplicated

ignore-paths:
  - tilecloud_chain/configuration.py

pylint:
  disable:
    - cyclic-import

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
  disable:
    - PLC0415 # `import` should be at the top-level of a file (present in pre-commit but not in checks)
