inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:c2cwsgiutils
  - duplicated

ignore-paths:
  - tilecloud_chain/configuration.py
  - tilecloud_chain/host_limit.py

pylint:
  disable:
    - cyclic-import

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
  disable:
    - BLE001 # Blind except added in ruff v0.16.0
    - CPY001 # Missing copyright notice added in ruff v0.16.0
    - ISC004 # Implicit string concatenation in collection added in ruff v0.16.0
    - PLC0415 # `import` should be at the top-level of a file (present in pre-commit but not in checks)
    - RUF036 # None not at end of union added in ruff v0.16.0
