inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:c2cwsgiutils
  - duplicated

ignore-paths:
  - tilecloud_chain/configuration.py

pylint:
  disable:
    - cyclic-import

mypy:
  options:
    python-version: '3.10'

ruff:
  options:
    target-version: py310
