inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:c2cwsgiutils
  - duplicated

ignore-paths:
  - tilecloud_chain/configuration.py
  - tilecloud_chain/host_limit.py

pylint:
  disable:
    - cyclic-import

mypy:
  options:
    python-version: '3.12'

ruff:
  options:
    target-version: py312
  disable:
    - BLE001 # No blind except (already suppressed with # noqa in the code)
    - PLC0415 # `import` should be at the top-level of a file (present in pre-commit but not in checks)
