services:
  application: &app
    ports:
      - '9050:8080'
    command:
      - /venv/bin/pserve
      - --reload
      - c2c:///app/application.ini
    environment:
      - DEVELOPMENT=TRUE
    volumes:
      - ./tilecloud_chain:/app/tilecloud_chain:ro
      # - ../tilecloud/tilecloud:/usr/local/lib/python3.10/dist-packages/tilecloud:ro

  app_test_user:
    <<: *app
    ports:
      - '9051:8080'

  slave:
    volumes:
      - ./tilecloud_chain:/app/tilecloud_chain:ro

  # test:
  #   volumes:
  #     - ./tilecloud_chain:/app/tilecloud_chain:ro
  #     - ../tilecloud/tilecloud:/usr/local/lib/python3.10/dist-packages/tilecloud:ro
