db:
  image: camptocamp/postgres:9.6
  environment:
    POSTGRES_USER: www-data
    POSTGRES_DB: tests
  volumes:
    - ./docker/test-db:/docker-entrypoint-initdb.d:ro

mapserver:
  image: camptocamp/mapserver:latest
  volumes:
    - ./docker/mapfile-docker:/etc/mapserver:ro
  links:
    - db:db
  user: www-data

mapcache:
  image: camptocamp/mapcache:latest
  volumes:
    - ./docker/mapcache-docker:/etc/mapcache:ro
  links:
    - mapserver:mapserver
    - memcached:memcached
  user: www-data

memcached:
  image: memcached:1.5
  user: www-data
  command:
    - memcached
    - --memory-limit=512

redis:
  image: redis:5
  user: www-data
  command:
    - redis-server
    - --save
    - ''
    - --appendonly
    - 'no'
    - --maxmemory
    - 512mb
    - --maxmemory-policy
    - allkeys-lru

test:
  image: camptocamp/tilecloud-chain:latest
  working_dir: /app
  environment:
    CI: "TRUE"
  command:
    - sleep
    - "3600"
  links:
    - db
    - mapcache
    - mapserver
    - redis
  volumes:
    - ./tilecloud_chain:/app/tilecloud_chain
