db:
  build: docker/test-db
  ports:
    - 5432:5432

mapserver:
  image: camptocamp/mapserver
  volumes:
    - ./tilecloud_chain/tests/mapfile-docker:/etc/mapserver
  links:
    - db:db
  ports:
    - 80:80

redis:
  image: redis:5
  user: www-data
  command:
    - redis-server
    - --save
    - ''
    - --appendonly
    - 'no'
    - --maxmemory
    - 512mb
    - --maxmemory-policy
    - allkeys-lru
  ports:
    - 6379:6379
