config:
  build: docker

db:
  image: camptocamp/postgres:9.6
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: tests
  volumes_from:
    - config

mapserver:
  image: camptocamp/mapserver:7.4
  environment:
    MS_DEBUGLEVEL: "5"
    MAPSERVER_CATCH_SEGV: "1"
  volumes_from:
    - config
  links:
    - db:db
  user: www-data

mapcache:
  image: camptocamp/mapcache:1.6
  volumes_from:
    - config
  links:
    - mapserver:mapserver
    - memcached:memcached
  user: www-data

memcached:
  image: memcached:1.5
  user: www-data
  command:
    - memcached
    - --memory-limit=512

redis:
  image: redis:5
  user: www-data
  command:
    - redis-server
    - --save
    - ''
    - --appendonly
    - 'no'
    - --maxmemory
    - 512mb
    - --maxmemory-policy
    - allkeys-lru

test:
  image: camptocamp/tilecloud-chain:latest
  working_dir: /app
  environment:
    CI: "TRUE"
    PGPASSWORD: postgres
  command:
    - sleep
    - "3600"
  links:
    - db
    - mapcache
    - mapserver
    - redis
