#!/bin/bash -e

NAME="camptocamp/tilecloud-chain"

function publish_docker {
    local version=$1
    docker_version=`echo "${version}" | sed -e 's/[\/:]/_/g'`

    echo "Deploying image to docker hub for tag ${docker_version}"
    docker tag "${NAME}:latest" "${NAME}:${docker_version}"
    docker push "${NAME}:${docker_version}"
}

function publish_pypi {
    local version=$1

    if curl --silent --fail "https://pypi.org/project/tilecloud_chain/${version}/" > /dev/null
    then
        echo "Already released ${version}"
        exit 0
    fi

    rm -rf dist
    python3 ./setup.py bdist_wheel
    twine upload dist/*.whl
}

if [[ -n "${CIRCLE_PULL_REQUEST}" ]]
then
    echo "Not deploying image for pull requests"
    exit 0
fi

if [[ "${CIRCLE_BRANCH}" == "master" ]]
then
  publish_docker latest
elif [[ -n "${CIRCLE_TAG}" ]]
then
  publish_docker "${CIRCLE_TAG}"
  if [[ "${CIRCLE_TAG}" == `python3 setup.py --version` ]]
  then
    echo "Uploading version ${CIRCLE_TAG} to pypi"
    publish_pypi "${CIRCLE_TAG}"
  fi
elif [[ -n "${CIRCLE_BRANCH}" ]]
then
  publish_docker "${CIRCLE_BRANCH}"
else
  echo "Not deploying image"
fi
