#!/usr/bin/python

import os
import stat
import subprocess  # nosec
import sys

if "GROUP_ID" not in os.environ:
    sys.exit("The GROUP_ID environment variable is required")

if "USER_ID" not in os.environ:
    sys.exit("The USER_ID environment variable is required")

if "USER_NAME" not in os.environ:
    sys.exit("The USER_NAME environment variable is required")

if "UMASK" not in os.environ:
    sys.exit("The UMASK environment variable is required")

subprocess.check_call(["groupadd", "-g", os.environ["GROUP_ID"], "geomapfish"])  # nosec
subprocess.check_call(  # nosec
    [
        "useradd",
        "--shell",
        "/bin/bash",
        "--uid",
        os.environ["USER_ID"],
        "--gid",
        os.environ["GROUP_ID"],
        os.environ["USER_NAME"],
    ],
)

run_file_name = "/tmp/run"  # nosec
with open(run_file_name, "w") as run_file:
    run_file.write("#!/usr/bin/python\n")
    run_file.write("import subprocess, os\n")
    run_file.write("os.umask(0o{})\n".format(os.environ["UMASK"]))
    run_file.write(f"subprocess.check_call({sys.argv[1:]!r})\n")

os.chmod(
    run_file_name,
    stat.S_IRUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
)
subprocess.check_call(["su", os.environ["USER_NAME"], "-c", run_file_name])  # nosec
