---
version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          dependency_type: all
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
    ignored_updates:
      - match:
          dependency_name: none

  - package_manager: docker
    directory: /
    update_schedule: weekly
