---

version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          dependency_type: direct
    automerged_updates:
      - match:
          update_type: all
    ignored_updates:
      - match:
          dependency_name: none
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: "1.11"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: "1.12"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: "1.13"
    allowed_updates:
      - match:
          update_type: security

  - package_manager: docker
    directory: /
    update_schedule: weekly
