#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import sys

import requests


def clean():
    token = requests.post(
        "https://hub.docker.com/v2/users/login/",
        headers={"Content-Type": "application/json"},
        data=json.dumps({"username": os.environ["USERNAME"], "password": os.environ["PASSWORD"]}),
    ).json()["token"]

    with open(os.environ["GITHUB_EVENT_PATH"]) as event_file:
        ref = json.loads(event_file.read())["ref"].replace("/", "_")

    print("Delete image 'camptocamp/mapserver:{}'.".format(ref))

    response = requests.head(
        "https://hub.docker.com/v2/repositories/camptocamp/mapserver/tags/{tag}/".format(tag=ref),
        headers={"Authorization": "JWT " + token},
    )
    if response.status_code == 404:
        return
    if not response.ok:
        print("Error checking image 'camptocamp/mapserver:{}' status.".format(ref))
        print(response.text)
        sys.exit(2)

    response = requests.delete(
        "https://hub.docker.com/v2/repositories/camptocamp/tileclouf-chain/tags/{tag}/".format(tag=ref,),
        headers={"Authorization": "JWT " + token,},
    )
    if not response.ok:
        print(response.text)
        sys.exit(2)


clean()
