#!/bin/bash -e

NAME="camptocamp/tilecloud-chain"

function publish_docker {
    local version=$1
    docker_version=`echo "${version}" | sed -e 's/[\/:]/_/g'`

    echo "Deploying image to docker hub for tag ${docker_version}"
    docker tag "${NAME}:latest" "${NAME}:${docker_version}"
    docker push "${NAME}:${docker_version}"
}

function publish_pypi {
    local version=$1

    if curl --silent --fail "https://pypi.org/project/tilecloud_chain/${version}/" > /dev/null
    then
        echo "Already released ${version}"
        exit 0
    fi

    rm -rf dist
    python3 ./setup.py bdist_wheel
    twine upload dist/*.whl
}

if [[ "${GITHUB_REF}" == "refs/heads/master" ]]
then
  publish_docker latest
elif [[ "${GITHUB_REF}" =~ "^refs/tags/.*" ]]
then
  GIT_TAG=$(echo "${GITHUB_REF}"|sed 's|^refs/tags/||g')
  publish_docker "${GIT_TAG}"
  if [[ "${GIT_TAG}" == `python3 setup.py --version` ]]
  then
    echo "Uploading version ${GIT_TAG} to pypi"
    publish_pypi "${GIT_TAG}"
  fi
elif [[ "${GITHUB_REF}" =~ "^refs/heads/.*" ]]
then
  GIT_BRANCH=$(echo "${GITHUB_REF}"|sed 's|^refs/heads/||g')
  publish_docker "${GIT_BRANCH}"
else
  echo "Not deploying image"
fi
