---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10

    env:
      REDIS_URL: redis://localhost:6379
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      - uses: actions/checkout@v1

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
        if: github.repository == 'camptocamp/tilecloud-chain'

      - run: touch tilecloud_chain/OpenLayers.js

      - name: Build
        run: |
          python setup.py --long-description > PYPI.md
          docker build --tag=camptocamp/tilecloud-chain:tests --target=tests .
          docker build --tag=camptocamp/tilecloud-chain .
          git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`

      - name: Test
        run: |
          docker-compose up -d

          # Wait for DB to be up
          while ! docker-compose exec -T test psql -h db -p 5432 -U postgres -v ON_ERROR_STOP=1 -c "SELECT 1" -d tests
          do
            echo "Waiting for DB to be UP"
            sleep 1
          done

          docker-compose exec -T test pytest

          docker-compose down

      - run: docker-compose logs
        if: failure()

      - name: Check Python package
        run: |
          sudo apt install --yes python3-setuptools python3-wheel
          python3 -m pip install --requirement=requirements-publish.txt
          python3 ./setup.py bdist_wheel
          twine check dist/*

      - run: |
          summon --yaml '
              USERNAME: !var gs/ci/pypi/username
              PASSWORD: !var gs/ci/pypi/password
            ' bash -c 'envsubst < ci/pypirc.tmpl > ~/.pypirc'
        if: github.repository == 'camptocamp/tilecloud-chain'
      - run: |
          mkdir  ~/.docker
          summon --yaml '
              TOKEN: !var gs/ci/dockerhub/token
            ' bash -c 'envsubst < ci/docker-config.json.tmpl > ~/.docker/config.json'
        if: github.repository == 'camptocamp/tilecloud-chain'

      - name: Publish
        run: ci/publish
