---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    env:
      REDIS_URL: redis://localhost:6379
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin

    steps:
      - uses: actions/checkout@v2

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker
        if: github.repository == 'camptocamp/tilecloud-chain'

      - run: touch tilecloud_chain/OpenLayers.js

      - name: Build
        run: |
          python setup.py --long-description > PYPI.md
          docker build --tag=camptocamp/tilecloud-chain:tests --target=tests .
          docker build --tag=camptocamp/tilecloud-chain .
          git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`

      - name: Test
        run: |
          docker-compose up -d

          # Wait for DB to be up
          while ! docker-compose exec -T test psql -h db -p 5432 -U postgres -v ON_ERROR_STOP=1 -c "SELECT 1" -d tests
          do
            echo "Waiting for DB to be UP"
            sleep 1
          done

          docker-compose exec -T test pytest

          docker-compose down

      - run: docker-compose logs
        if: failure()

      - name: Check Python package
        run: |
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install --yes python3-setuptools python3-wheel
          python3 -m pip install --requirement=requirements-publish.txt
          python3 ./setup.py bdist_wheel
          twine check dist/*

      - name: Publish
        run: ci/publish
