---

name: Clean docker hub tags

on:
  delete

jobs:
  clean:
    runs-on: ubuntu-18.04
    name: Clean docker hub tags
    timeout-minutes: 5
    env:
      SUMMON_PROVIDER: /usr/local/bin/gopass
    steps:
      - uses: actions/checkout@v1
      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          large-secret-passphrase: ${{secrets.LARGE_SECRET_PASSPHRASE}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
      - name: Clean docker hub tags
        run: |
          summon '
              USERNAME: !var gs/ci/dockerhub/username
              PASSWORD: !var gs/ci/dockerhub/password
            ' ci/clean-dockerhub-tag
