name: Continuous integration

on:
  push:
  pull_request:

permissions:
  contents: write
  packages: write
  id-token: write

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    env:
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install setuptools==68.0.0 wheel==0.45.1

      - run: python3 -m pip install --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      # Pinned to 2.2.0 because 2.3.0 fails with false positives due to unpinned transitive dependencies drift
      - run: sudo npm install --global json-schema-spell-checker@2.2.0
      - run: json-schema-spell-checker --fields=description,title --spelling=.spelling --ignore-numbers tilecloud_chain/schema.json

      - name: Build
        run: make build

      - name: Tests
        run: make tests

      - run: c2cciutils-docker-logs
        if: always()

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: tag-publish-python
        with:
          python-version: '3.11'
          update-environment: false
      - run: ${{ steps.tag-publish-python.outputs.python-path }} -m venv ${HOME}/.tag-publish
      - run: ${HOME}/.tag-publish/bin/pip install tag-publish==1.2.6
      - name: Publish
        run: ${HOME}/.tag-publish/bin/tag-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.HAS_SECRETS == 'HAS_SECRETS'
      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
