name: Rebuild

on:
  schedule:
    - cron: 30 2 * * *

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: '1.17'

    env:
      REDIS_URL: redis://localhost:6379

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@17703c87720ba3766abc90da60b437783b530d93 # v2.0.1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
      - run: python3 -m pip install setuptools==76.1.0 wheel==0.45.1
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Build
        run: make build

      - name: Tests
        run: make tests

      - run: c2cciutils-docker-logs
        if: always()

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
